let DefaultSentryCost = 2;
module.exports = {
    damage_sentry:{
        Namespace: "Damage",
        Lifetime: 15,
        Target: "#nightrunner:enemy",
        Distance: 6,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 3,
        ManaCost: DefaultSentryCost,
    },
    heal_sentry:{
        Namespace: "Heal",
        Lifetime: 5,
        Target: "player",
        Distance: 6,
        DustColor: "0.0,1.0,0.0",
        DisplayBlock: "minecraft:beacon",
        ConcurrentAttacks: 3,
        ManaCost: 15,
    },
    wooden_sentry:{
        Namespace: "Wooden",
        Lifetime: 13,
        Target: "#nightrunner:enemy",
        Distance: 6,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 1,
        ManaCost: DefaultSentryCost,
    },
    stone_sentry:{
        Namespace: "Stone",
        Lifetime: 14,
        Target: "#nightrunner:enemy",
        Distance: 7,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 2,
        ManaCost: DefaultSentryCost,
    },
    iron_sentry:{
        Namespace: "Iron",
        Lifetime: 16,
        Target: "#nightrunner:enemy",
        Distance: 8,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 3,
        ManaCost: DefaultSentryCost,
    },
    golden_sentry:{
        Namespace: "Golden",
        Lifetime: 15,
        Target: "#nightrunner:enemy",
        Distance: 5,
        DustColor: "0.973,1.000,0.212",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 5,
        ManaCost: DefaultSentryCost,
    },
    diamond_sentry:{
        Namespace: "Diamond",
        Lifetime: 18,
        Target: "#nightrunner:enemy",
        Distance: 10,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 4,
        ManaCost: DefaultSentryCost,
    },
}