module.exports = {
    damage_sentry:{
        Namespace: "Damage",
        Lifetime: 15,
        Target: "#nightrunner:enemy",
        Distance: 6,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 3,
    },
    heal_sentry:{
        Namespace: "Heal",
        Lifetime: 5,
        Target: "player",
        Distance: 6,
        DustColor: "0.0,1.0,0.0",
        DisplayBlock: "minecraft:beacon",
        ConcurrentAttacks: 3,
    },
    wooden_sentry:{
        Namespace: "Wooden",
        Lifetime: 10,
        Target: "#nightrunner:enemy",
        Distance: 3,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 1,
    },
    stone_sentry:{
        Namespace: "Stone",
        Lifetime: 10,
        Target: "#nightrunner:enemy",
        Distance: 3,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 2,
    },
    iron_sentry:{
        Namespace: "Iron",
        Lifetime: 15,
        Target: "#nightrunner:enemy",
        Distance: 5,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 3,
    },
    golden_sentry:{
        Namespace: "Golden",
        Lifetime: 5,
        Target: "#nightrunner:enemy",
        Distance: 3,
        DustColor: "0.973,1.000,0.212",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 5,
    },
    diamond_sentry:{
        Namespace: "Diamond",
        Lifetime: 20,
        Target: "#nightrunner:enemy",
        Distance: 5,
        DustColor: "1.0,0.0,0.0",
        DisplayBlock: "minecraft:calibrated_sculk_sensor",
        ConcurrentAttacks: 4,
    },
}