// Description: This file contains the wand data for the Nightrunner datapack.
module.exports = {
    wooden_wand : {
        Name: "Wooden Wand",
        Color: "white",
        Folder: "wands",
        Description: "Damage: 4 | Cooldown: 8",
        Cooldown: 8,
        Particle: "minecraft:crit",
        CustomModelData: 1121,
        Namespace: "wooden_wand",
        FunctionName: "wooden",
        MainSpell: "Damage",
        SecondarySpell: "Damage",
        SpellDamage: 4,
        HealAmount: 0,
        HitType: 1,
    },
    stone_wand: {
        Name: "Stone Wand",
        Color: "white",
        Folder: "wands",
        Description: "Damage: 5 | Cooldown: 8",
        Cooldown: 8,
        Particle: "minecraft:crit",
        CustomModelData: 1122,
        Namespace: "stone_wand",
        FunctionName: "stone",
        MainSpell: "Damage",
        SecondarySpell: "Damage",
        SpellDamage: 5,
        HealAmount: 0,
        HitType: 1,
    },
    iron_wand: {
        Name: "Iron Wand",
        Color: "white",
        Folder: "wands",
        Description: "Damage: 6 | Cooldown: 8",
        Cooldown: 8,
        Particle: "minecraft:crit",
        CustomModelData: 1123,
        Namespace: "iron_wand",
        FunctionName: "iron",
        MainSpell: "Damage",
        SecondarySpell: "Damage",
        SpellDamage: 6,
        HealAmount: 0,
        HitType: 1,
    },
    golden_wand: {
        Name: "Golden Wand",
        Color: "white",
        Folder: "wands",
        Description: "Damage: 11 | Cooldown: 16",
        Cooldown: 16,
        Particle: "minecraft:crit",
        CustomModelData: 1124,
        Namespace: "golden_wand",
        FunctionName: "golden",
        MainSpell: "Damage",
        SecondarySpell: "Damage",
        SpellDamage: 11,
        HealAmount: 0,
        HitType: 1,
    },
    diamond_wand: {
        Name: "Diamond Wand",
        Color: "white",
        Folder: "wands",
        Description: "Damage: 7 | Cooldown: 8",
        Cooldown: 8,
        Particle: "minecraft:crit",
        CustomModelData: 1125,
        Namespace: "diamond_wand",
        FunctionName: "diamond",
        MainSpell: "Damage",
        SecondarySpell: "Damage",
        SpellDamage: 7,
        HealAmount: 0,
        HitType: 1,
    }
}